### ISSUE TITLE
Rework the Download Data Section

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/website#16]
data.md makes no mention of the file manager and its capability to download data directly. This section is dating back to the PDA versions which had no wifi or other connectivity and file operations had to be done manually.

Please rework this section and remove the individual links to data-files. We already maintain these in xcsoar-data-repository.

**Comment by rawtaz** [comment]
Looking at the PR @mlep submitted I'm not sure that's the best way to change this information. In it, good-to-have pointers have been removed, e.g. the FLARM file, not to mention the map generator. I think we should keep those.

Changed should be made so that people know they don't *have* to manually populate data in XCSoar, but keeping references to useful data sources is good (IMO). But perhaps those pointers are already collected in some other place, and we can just point to that instead (for those interested in data sources or manually fetching data)?

@mlep Please note that you have a bunch of spelling mistakes in the PR, would be nice to have those fixed :)

**Comment by mlep** [comment]
@rawtaz  It looks like I misunderstood issue #16. Now a new version with minimal changes. Please, alter as needed.

**Comment by lordfolken** [comment]
closing. Thx @mlep :+1:
